name: countries
on:
  # On push to the countries package
  push:
    paths:
      - ./.github/workflows/countries.yml
      - ./packages/countries/**
  # Or whenever run by hand
  workflow_dispatch:
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm
      - run: npm ci
      - run: npm run -w packages/countries lint
      - run: npm run -w packages/countries test

  node-versions:
    name: node-${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node: [ 12, 14, 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use node-${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run -w packages/countries test
